# Generated by Django 5.2.4 on 2025-12-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0005_alter_lessontest_bg'),
        ('app_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app_lesson.lessontest'),
        ),
    ]
