# Generated by Django 5.2.4 on 2025-10-08 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GophishEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('gophish_time', models.DateTimeField()),
                ('message', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'message'], name='gophish_gop_user_id_b52fa1_idx'), models.Index(fields=['gophish_time'], name='gophish_gop_gophish_ecd84d_idx')],
            },
        ),
    ]
