# Generated by Django 5.2.4 on 2025-11-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gophish', '0004_gophishconsent_userphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumber',
            name='dummy_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
