# Generated by Django 5.2.4 on 2025-11-21 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gophish', '0005_userphonenumber_dummy_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GophishUserScoreSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sent', models.PositiveIntegerField(default=0)),
                ('links_clicked', models.PositiveIntegerField(default=0)),
                ('data_submitted', models.PositiveIntegerField(default=0)),
                ('security_score', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
