# Generated by Django 5.2.4 on 2025-11-30 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gophish', '0006_gophishuserscoresms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gophishevent',
            name='type',
            field=models.CharField(default='email', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gophishevent',
            index=models.Index(fields=['type'], name='gophish_gop_type_1fdb3a_idx'),
        ),
    ]
