from django.contrib.auth.models import User
from django.urls import reverse
from django.test import TestCase
from rest_framework.test import APIClient
from rest_framework import status

from app_modules.models import ModuleTest, ModuleSource, UserModuleTestProgress
from app_lesson.models import LessonTest
from app_section.models import Section


class ModuleTestModelTests(TestCase):
    def setUp(self):
        self.lesson1 = LessonTest.objects.create(title="Lesson 1", lesson_order=1)
        self.lesson2 = LessonTest.objects.create(title="Lesson 2", lesson_order=2)
        # Section requires lesson and description
        self.section = Section.objects.create(lesson=self.lesson1, name="Section A", description="desc")

    def test_slug_and_module_order_autogenerated(self):
        mt1 = ModuleTest.objects.create(
            lesson=self.lesson1,
            section=self.section,
            title="Intro Module",
            final=False,
        )
        mt2 = ModuleTest.objects.create(
            lesson=self.lesson1,
            section=self.section,
            title="Intro Module",  # same title, slug should be uniquified
            final=False,
        )

        self.assertIsNotNone(mt1.slug)
        self.assertIsNotNone(mt2.slug)
        self.assertNotEqual(mt1.slug, mt2.slug)

        # module_order should be incremental within the same lesson
        self.assertEqual(mt1.module_order, 1)
        self.assertEqual(mt2.module_order, 2)

    def test_unlocks_lesson_logic_non_final_sets_current(self):
        mt = ModuleTest.objects.create(
            lesson=self.lesson1,
            section=self.section,
            title="Module",
            final=False,
        )
        self.assertEqual(mt.unlocks_lesson, self.lesson1)

    def test_unlocks_lesson_logic_final_sets_next_lesson(self):
        mt = ModuleTest.objects.create(
            lesson=self.lesson1,
            section=self.section,
            title="Final Module",
            final=True,
        )
        self.assertEqual(mt.unlocks_lesson, self.lesson2)


class ModuleTestViewSetTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(username="tester", password="pass1234")
        self.client.force_authenticate(user=self.user)

        self.lesson = LessonTest.objects.create(title="Lesson A", lesson_order=1)
        self.section = Section.objects.create(lesson=self.lesson, name="Section B", description="desc")

        self.mt = ModuleTest.objects.create(
            lesson=self.lesson,
            section=self.section,
            title="Module A",
            final=False,
        )

    def test_create_user_module_test_progress_endpoint(self):
        url = reverse("usermoduletestprogress-list")
        # First call should create (201)
        resp1 = self.client.post(url, {"module_test": self.mt.id}, format="json")
        self.assertEqual(resp1.status_code, status.HTTP_201_CREATED)
        self.assertEqual(UserModuleTestProgress.objects.filter(user=self.user, module_test=self.mt).count(), 1)

        # Second call should update_or_create existing and return 202
        resp2 = self.client.post(url, {"module_test": self.mt.id}, format="json")
        self.assertEqual(resp2.status_code, status.HTTP_202_ACCEPTED)
        self.assertEqual(UserModuleTestProgress.objects.filter(user=self.user, module_test=self.mt).count(), 1)

    def test_unlocked_modules_endpoint(self):
        # Initially none
        url = reverse("moduletest-unlocked-module-test")
        resp_initial = self.client.get(url)
        self.assertEqual(resp_initial.status_code, status.HTTP_200_OK)
        self.assertEqual(resp_initial.json(), [])

        # Create progress and expect slug returned
        UserModuleTestProgress.objects.create(user=self.user, module_test=self.mt)
        resp_after = self.client.get(url)
        self.assertEqual(resp_after.status_code, status.HTTP_200_OK)
        self.assertIn(self.mt.slug, resp_after.json())


class ModuleSourceViewSetTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(username="tester2", password="pass1234")
        self.client.force_authenticate(user=self.user)

        self.lesson = LessonTest.objects.create(title="Lesson B", lesson_order=1)
        self.section = Section.objects.create(lesson=self.lesson, name="Section C", description="desc")
        self.mt = ModuleTest.objects.create(
            lesson=self.lesson,
            section=self.section,
            title="Module B",
            final=False,
        )
        self.src1 = ModuleSource.objects.create(module=self.mt, title="Doc 1", url="https://example.com/1")
        self.src2 = ModuleSource.objects.create(module=self.mt, title="Doc 2", url="https://example.com/2")

    def test_get_by_module_returns_sources(self):
        url = reverse("modulesource-get-by-module")
        resp = self.client.get(url, {"module_id": self.mt.id})
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        data = resp.json()
        titles = {item["title"] for item in data}
        self.assertSetEqual(titles, {self.src1.title, self.src2.title})

    def test_get_by_module_without_param_returns_404(self):
        url = reverse("modulesource-get-by-module")
        resp = self.client.get(url)
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)
