# Generated by Django 5.2.4 on 2025-12-06 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='malvertising', max_length=50)),
                ('difficulty', models.CharField(default='normal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PopupTriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_triggered', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('clicked', 'Clicked'), ('closed', 'Closed')], default='waiting', max_length=20)),
                ('reaction_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_popup.popupscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scenario', 'date_triggered')},
            },
        ),
    ]
