# Generated by Django 5.2.4 on 2025-08-07 04:13

import django.db.models.deletion
from django.db import migrations, models

def add_rank_data(apps, schema_editor):
    rank = apps.get_model('app_level', 'Rank')
    
    # Create initial lessons
    rank.objects.create(name="Bronze", min_level=1)
    rank.objects.create(name="Silver", min_level=4)
    
    
def add_level_data(apps, schema_editor):
    level = apps.get_model('app_level', 'Level')
    
    # Create initial lessons
    level.objects.create(number=1, xp_required=100, name="Beginner", rank_id=1)
    level.objects.create(number=2, xp_required=200, name="Beginner", rank_id=1)
    level.objects.create(number=3, xp_required=350, name="Beginner", rank_id=1)
    level.objects.create(number=4, xp_required=600, name="Novice", rank_id=2)
    level.objects.create(number=5, xp_required=800, name="Novice", rank_id=2)
    
    
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_level', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['min_level'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('xp_required', models.PositiveIntegerField(default=0)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='app_level.rank')),
            ],
            options={
                'ordering': ['xp_required'],
            },
        ),
        
        migrations.RunPython(add_rank_data),
        migrations.RunPython(add_level_data),
    ]
