# Generated by Django 5.2.4 on 2025-08-29 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def add_badge_data(apps, schema_editor):
    badge = apps.get_model('app_badge', 'Badge')
    lesson = apps.get_model('app_lesson', 'Lesson')
    
    socialEngineering = lesson.objects.get(id=1)
    badge.objects.create(name="Social Engineering", lesson=socialEngineering)
    
    phishing = lesson.objects.get(id=2)
    badge.objects.create(name="Phishing", lesson=phishing)
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='app_lesson.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_badge.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badge',
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(related_name='badges', through='app_badge.UserBadge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_badge_data),
    ]
