# Generated by Django 5.2.4 on 2026-01-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_badge', '0002_alter_badge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
