# Generated by Django 5.2.4 on 2026-01-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_badge', '0003_alter_badge_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('streak', 'Streak'), ('completion', 'Completion'), ('count', 'Count')], default='count', max_length=20)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('target_entity', models.CharField(choices=[('login', 'Login'), ('lesson', 'Lesson'), ('module', 'Module'), ('quiz', 'Quiz')], max_length=50)),
                ('target_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge'),
        ),
        migrations.AddField(
            model_name='badgerule',
            name='badge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge_rule', to='app_badge.badge'),
        ),
    ]
