# Generated by Django 5.2.4 on 2025-11-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assessment', '0002_assessment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='props',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='instructions',
            field=models.JSONField(default=dict),
        ),
    ]
