# Generated by Django 5.2.4 on 2025-11-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assessment', '0004_alter_assessment_instructions_assessmentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='completed_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_assessment.question')),
                ('selected_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_assessment.option')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_assessment.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_answer',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
