# Generated by Django 5.2.4 on 2025-11-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assessment', '0005_assessmentsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='not_started', max_length=20),
        ),
    ]
