# Generated by Django 5.2.4 on 2025-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assessment', '0007_assessment_passing_rate_assessmentcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='passing_rate',
            field=models.FloatField(default=75, help_text='Passing rate as a percentage'),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
