# Generated by Django 5.2.4 on 2025-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assessment', '0008_alter_assessment_passing_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='required_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum user level required to unlock'),
        ),
    ]
