# Generated by Django 5.2.4 on 2026-01-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assessment', '0009_assessment_required_level'),
        ('app_modules', '0006_modulesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='recommended_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_answers', to='app_modules.moduletest'),
        ),
        migrations.AddField(
            model_name='question',
            name='related_module',
            field=models.ForeignKey(blank=True, help_text='Optional: the module to recommend when users answer this question incorrectly', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_assessment_questions', to='app_modules.moduletest'),
        ),
    ]
