export {default as WhatIsSocialEngineering} from './WhatIsSocialEngineering/index.vue'
export { default as CommonAttacks } from './CommonAttacks/index.vue'
export { default as FinalQuiz } from './FinalQuiz.vue'
export { default as HowToProtectYourself } from './HowToProtectYourself/index.vue'
export { default as InteractiveScenarioSpotTheAttack } from './InteractiveScenarioSpotTheAttack/index.vue'
export { default as PsychologicalPrinciplesUsed } from './PsychologicalPrinciplesUsed/index.vue'
