# Generated by Django 5.2.4 on 2025-09-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0001_initial'),
        ('app_modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='modules',
        ),
        migrations.AddField(
            model_name='content',
            name='modules',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app_modules.modules'),
            preserve_default=False,
        ),
    ]
