# Generated by Django 5.2.4 on 2025-09-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0003_contentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='item_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='props',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('LearningSection', 'Learning Section'), ('LearningHeader', 'Learning Header'), ('LearningBody', 'Learning Body'), ('LearningList', 'Learning List'), ('LearningListItem', 'Learning List Item'), ('LearningQuote', 'Learning Quote'), ('InteractiveMCQ', 'Interactive MCQ'), ('LearningImage2', 'Learning Image2')], max_length=50),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_contents.contentitem')),
            ],
        ),
    ]
