# Generated by Django 5.2.4 on 2025-09-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0004_alter_contentitem_item_order_alter_contentitem_props_and_more'),
        ('app_modules', '0002_moduletest_usermoduletestprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app_modules.moduletest'),
        ),
    ]
