# Generated by Django 5.2.4 on 2025-09-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0005_alter_content_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContentQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LearningSection', 'Learning Section')], max_length=50)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_quiz', to='app_contents.content')),
            ],
        ),
    ]
