# Generated by Django 5.2.4 on 2025-09-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0006_alter_content_content_order_contentquiz'),
        ('app_modules', '0002_moduletest_usermoduletestprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentquiz',
            name='content',
        ),
        migrations.AddField(
            model_name='contentquiz',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_quiz', to='app_modules.moduletest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentquiz',
            name='type',
            field=models.CharField(choices=[('DoDont', 'Do and Dont')], max_length=50),
        ),
    ]
