# Generated by Django 5.2.4 on 2025-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0007_remove_contentquiz_content_contentquiz_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentquiz',
            name='type',
            field=models.CharField(choices=[('DoDont', 'Do and Dont'), ('MultipleChoice', 'Multiple Choice'), ('MatchingType', 'Matching Type'), ('DragPair', 'Drag Pair'), ('ModuleReward', 'Module Reward')], max_length=50),
        ),
    ]
