# Generated by Django 5.2.4 on 2025-09-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0008_alter_contentquiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentquiz',
            name='type',
            field=models.CharField(choices=[('DoDont', 'Do and Dont'), ('MultipleChoice', 'Multiple Choice'), ('MatchingType', 'Matching Type'), ('DragPair', 'Drag Pair'), ('ModuleReward', 'Module Reward'), ('FinalTest', 'Final Test')], max_length=50),
        ),
        migrations.CreateModel(
            name='ContentQuizImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_quiz/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_contents.contentquiz')),
            ],
        ),
    ]
