# Generated by Django 5.2.4 on 2025-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0010_alter_contentitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentquiz',
            name='quiz_limit',
            field=models.IntegerField(default=1),
        ),
    ]
