# Generated by Django 5.2.4 on 2025-09-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0011_contentquiz_quiz_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentquiz',
            name='pass_rate',
            field=models.IntegerField(default=1),
        ),
    ]
