# Generated by Django 5.2.4 on 2025-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0012_contentquiz_pass_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentquiz',
            name='type',
            field=models.CharField(choices=[('DoDont', 'Do and Dont'), ('MultipleChoice', 'Multiple Choice'), ('MatchingType', 'Matching Type'), ('DragPair', 'Drag Pair'), ('ModuleReward', 'Module Reward'), ('ScenarioTraining', 'Scenario Training'), ('FinalTest', 'Final Test')], max_length=50),
        ),
    ]
