# Generated by Django 5.2.4 on 2025-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0013_alter_contentquiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('LearningSection', 'Learning Section'), ('LearningHeader', 'Learning Header'), ('LearningBody', 'Learning Body'), ('LearningList', 'Learning List'), ('LearningListItem', 'Learning List Item'), ('LearningListItemNumbered', 'Learning List Item Numbered'), ('LearningQuote', 'Learning Quote'), ('InteractiveMCQ', 'Interactive MCQ'), ('LearningImage2', 'Learning Image2'), ('FlippingCard', 'Flipping Card'), ('DescriptionList', 'Description List'), ('TwoImage', 'Two Image')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contentquiz',
            name='type',
            field=models.CharField(choices=[('DoDont', 'Do and Dont'), ('MultipleChoice', 'Multiple Choice'), ('MatchingType', 'Matching Type'), ('DragPair', 'Drag Pair'), ('PhishingTactics', 'Phishing Tactics'), ('ModuleReward', 'Module Reward'), ('ScenarioTraining', 'Scenario Training'), ('FinalTest', 'Final Test')], max_length=50),
        ),
    ]
