# Generated by Django 5.2.4 on 2025-11-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0014_alter_contentitem_type_alter_contentquiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('LearningSection', 'Learning Section'), ('LearningHeader', 'Learning Header'), ('LearningBody', 'Learning Body'), ('LearningList', 'Learning List'), ('LearningListItem', 'Learning List Item'), ('LearningListItemNumbered', 'Learning List Item Numbered'), ('LearningQuote', 'Learning Quote'), ('InteractiveMCQ', 'Interactive MCQ'), ('LearningImage2', 'Learning Image2'), ('FlippingCard', 'Flipping Card'), ('DescriptionList', 'Description List'), ('TwoImage', 'Two Image'), ('ToolTipImage', 'Tool Tip Image'), ('NextCard', 'Next Card')], max_length=50),
        ),
    ]
