# Generated by Django 5.2.4 on 2025-08-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_predefined_items(apps, schema_editor):
    Item = apps.get_model('app_cosmetic', 'Item')
    Item.objects.create(
        name="Christmas Background",
        type="background",
        price=500,
        image="items/christmasBackground@3x.webp"
    )
    Item.objects.create(
        name="Yellow Background",
        type="background",
        price=0,
        image="items/cityscape-yellow3x.png"
    )
    Item.objects.create(
        name="Purple",
        type="avatar",
        price=0,
        image="items/robotpurple.png",
        rive_code=0
    )
    Item.objects.create(
        name="Orange",
        type="avatar",
        price=0,
        image="items/robotOrange.png",
        rive_code=1
    )
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('avatar', 'Avatar'), ('background', 'Background')], max_length=20)),
                ('image', models.ImageField(upload_to='items/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('rive_code', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BackpackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cosmetic.item')),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserCosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped_avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_avatar', to='app_cosmetic.backpackitem')),
                ('equipped_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_background', to='app_cosmetic.backpackitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_predefined_items),
    ]
