# Generated by Django 5.2.4 on 2025-12-21 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cosmetic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avatarfile',
            field=models.FileField(blank=True, null=True, upload_to='items/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp', 'riv'])]),
        ),
    ]
