# Generated by Django on 2025-12-08
from django.db import migrations


def create_default_minigames(apps, schema_editor):
    MiniGame = apps.get_model('app_minigame', 'MiniGame')

    defaults = [
        {
            'name': 'Rocket Password',
            'route_path': '/minigames/rocket',
            'card_color': '#131c30',
            'required_level': 1,
            'is_daily': False,
            'thumbnail': None,
        },
        {
            'name': 'Guess Word',
            'route_path': '/minigames/guess-word',
            'card_color': '#75bd3d',
            'required_level': 1,
            'is_daily': False,
            'thumbnail': None,
        },
        {
            'name': 'Whack a Mole',
            'route_path': '/minigames/whack-a-mole',
            'card_color': '#f6c298',
            'required_level': 1,
            'is_daily': False,
            'thumbnail': None,
        },
    ]

    for data in defaults:
        # Avoid duplicates by name
        if not MiniGame.objects.filter(name=data['name']).exists():
            MiniGame.objects.create(**data)


def remove_default_minigames(apps, schema_editor):
    MiniGame = apps.get_model('app_minigame', 'MiniGame')
    names = ['Rocket Password', 'Guess Word', 'Whack a Mole']
    MiniGame.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app_minigame', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_minigames, remove_default_minigames),
    ]