# Generated by Django on 2025-12-08
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_minigame', '0002_default_minigames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigame',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='minigames/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
