# Generated by Django 5.2.4 on 2025-12-01 04:48

import app_quizzes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_modules', '0005_moduletest_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('quiz_type', models.CharField(default=1, verbose_name=app_quizzes.models.QuizType)),
                ('total_questions', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(blank=True, default=1, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('accuracy', models.FloatField(default=0.0)),
                ('pass_fail', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to='app_modules.moduletest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
