# Generated by Django 5.2.4 on 2025-09-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modules', '0004_moduletest_users'),
        ('app_quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_modules.moduletest'),
        ),
    ]
