# Generated by Django 5.2.4 on 2025-09-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quizzes', '0002_alter_quizprogress_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='pass_fail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
