# Generated by Django 5.2.4 on 2025-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quizzes', '0003_quizprogress_accuracy_quizprogress_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogress',
            name='time_spent',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
