# Generated by Django 5.2.4 on 2025-09-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modules', '0005_moduletest_section'),
        ('app_quizzes', '0004_alter_quizprogress_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to='app_modules.moduletest'),
        ),
    ]
