# Generated by Django 5.2.4 on 2026-04-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commons.agreementsection'),
        ),
    ]
