# Generated by Django 5.2.4 on 2026-04-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commons', '0002_alter_agreement_agreement_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='app_commons.agreementsection'),
        ),
    ]
