# Generated by Django 5.2.4 on 2026-04-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commons', '0003_alter_agreement_agreement_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='simulationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('safeBrowsing', 'Safe Browsing'), ('phishing', 'Phishing'), ('smishing', 'Smishing'), ('vishing', 'Vishing')], max_length=50)),
                ('image', models.ImageField(upload_to='simulation/guides/')),
                ('image_alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
