# Generated by Django 5.2.4 on 2026-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commons', '0004_simulationguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationguide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='simulation/guides/'),
        ),
    ]
