# Generated by Django 5.2.4 on 2026-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commons', '0005_alter_simulationguide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationguide',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
