# Generated by Django 5.2.4 on 2025-07-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def add_module_data(apps, schema_editor):
    Lesson = apps.get_model('app_lesson', 'lesson')
    Module = apps.get_model('app_modules', 'modules')
    
    get_lesson = Lesson.objects.get(pk=1) 
    
    Module.objects.create(name="whatisSocialEngineering", phase_order=1, lesson=get_lesson)
    Module.objects.create(name="psychologicalPrinciplesUsed", phase_order=2, lesson=get_lesson)
    Module.objects.create(name="typesOfSocialEngineeringAttacks", phase_order=3, lesson=get_lesson)
    Module.objects.create(name="interactiveScenarioSpotTheAttack", phase_order=4, lesson=get_lesson)
    Module.objects.create(name="howToProtectYourself", phase_order=5, lesson=get_lesson)
    Module.objects.create(name="finalQuiz", phase_order=6, lesson=get_lesson)
    
    get_phishing = Lesson.objects.get(name="phishing") 
    
    Module.objects.create(name="phishingIntro", phase_order=7, lesson=get_phishing)
class Migration(migrations.Migration):

    
    initial = True

    dependencies = [
        ('app_lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app_lesson.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_modules.modules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_module_progress',
            },
        ),
        migrations.AddField(
            model_name='modules',
            name='users',
            field=models.ManyToManyField(related_name='modules', through='app_modules.UserModuleProgress', to=settings.AUTH_USER_MODEL),
        ),
        
        migrations.RunPython(add_module_data),
    ]
