# Generated by Django 5.2.4 on 2025-09-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0003_alter_lessontest_lesson_order_alter_lessontest_slug'),
        ('app_modules', '0002_moduletest_usermoduletestprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletest',
            name='module_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduletest',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='moduletest',
            name='unlocks_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_module_tests', to='app_lesson.lessontest'),
        ),
    ]
