# Generated by Django 5.2.4 on 2025-09-15 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modules', '0003_alter_moduletest_module_order_alter_moduletest_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletest',
            name='users',
            field=models.ManyToManyField(related_name='modules_test', through='app_modules.UserModuleTestProgress', to=settings.AUTH_USER_MODEL),
        ),
    ]
