# Generated by Django 5.2.4 on 2025-09-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modules', '0004_moduletest_users'),
        ('app_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletest',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app_section.section'),
            preserve_default=False,
        ),
    ]
