# Generated by Django 5.2.4 on 2025-12-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modules', '0005_moduletest_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='app_modules.moduletest')),
            ],
        ),
    ]
