# Generated by Django 5.2.4 on 2026-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modules', '0006_modulesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesource',
            name='author',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modulesource',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulesource',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
