# Generated by Django 5.2.4 on 2025-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_daily', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstreak',
            name='streak_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
