# Generated by Django 5.2.4 on 2025-07-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_lesson_data(apps, schema_editor):
    Lesson = apps.get_model('app_lesson', 'Lesson')
    
    # Create initial lessons
    Lesson.objects.create(name="introToSocialEngineering")
    Lesson.objects.create(name="phishing")
    
    
    
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lesson.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lesson_progress',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='users',
            field=models.ManyToManyField(related_name='lesson', through='app_lesson.UserLessonProgress', to=settings.AUTH_USER_MODEL),
        ),
        
        migrations.RunPython(add_lesson_data),
    ]
