# Generated by Django 5.2.4 on 2025-09-11 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_tests/images/')),
                ('bg', models.CharField(max_length=7)),
                ('lesson_order', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'lesson_test',
            },
        ),
        migrations.CreateModel(
            name='UserLessonTestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lesson.lessontest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lesson_test_progress',
            },
        ),
    ]
