# Generated by Django 5.2.4 on 2025-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0002_lessontest_userlessontestprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontest',
            name='lesson_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
