# Generated by Django 5.2.4 on 2025-11-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0003_alter_lessontest_lesson_order_alter_lessontest_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontest',
            name='objective',
            field=models.JSONField(default=list),
        ),
    ]
