# Generated by Django 5.2.4 on 2025-11-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0004_lessontest_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontest',
            name='bg',
            field=models.CharField(default='#5a2653', max_length=7),
        ),
    ]
