# Generated by Django 5.2.4 on 2025-08-03 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('reason', models.CharField(choices=[('content', 'content'), ('quiz', 'Quiz'), ('bonus', 'Bonus'), ('spend', 'Spend'), ('admin', 'Admin Adjustment')], max_length=20)),
                ('coin', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
