# Generated by Django 5.2.4 on 2025-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardlog',
            name='reason',
            field=models.CharField(choices=[('content', 'content'), ('quiz', 'Quiz'), ('bonus', 'Bonus'), ('spend', 'Spend'), ('assessment', 'Assessment'), ('admin', 'Admin Adjustment')], max_length=20),
        ),
    ]
